### ISSUE TITLE
Set Resolution Bandwidth

### ISSUE THREAD

**Issue by Apoplectic1** [arocholl/rfexplorer#8]
Thanks for a very useful product and API. I'm still brand new to it. 

Can't seem to figure out how to set Resolution Bandwidth from a PC to the Spectrum Analyzer with firmware 1.15. I would have guessed this would be part of the #C2-F: command. Going to check the RF Explorer for Windows project...

Thanks - Dan

**Comment by DF4OR** [comment]
With command #C2-F you set the start and end frequency of the sweep range, plus the amplitude range. RBW can not be set, it is always calculated by the device itself. That makes handling the RFexplorer quite simple. Please see the user manual and the serial port protocol in the wiki.

Disclaimer: I am in no way involved in the SW or HW development of RFExplorer, I am just a happy user.

**Comment by Apoplectic1** [comment]
That makes sense. Thank you for the quick reply!

 

-          Dan
